@startuml foco

class Usuario
class Foco
class EstadoFoco

Usuario o-- Foco
Foco *-- EstadoFoco
EstadoFoco --|> Booleano

class Foco{
    - EstadoFoco estado
    + Encender()
    + Apagar()
    + LeerEstado() : EstadoFoco
}

@enduml